spring.application.name=todolist
spring.profiles.active=local
server.port=${PORT:8080}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
